source 'https://rubygems.org'
gem 'ffi', '~> 1.9.24'
gem 'github-pages', '~> 192'
gem 'jekyll', '~> 3.7'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'kramdown'
gem 'nokogiri', '~> 1.8.1'
gem 'rake', '10.4.2'
gem 'rouge'
gem 'rubyzip', '~> 1.2.2'
